# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on: [push, pull_request]


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
          os: [ubuntu-latest]
          pytorch-version: [1.0.1, 1.1.0]
          python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt-get update -qq
        sudo apt-get install -qq -y cmake g++-7 libsndfile1-dev
    - name: install torch
      env:
        TH_VERSION: ${{ matrix.pytorch-version }}
      run: |
        pip install numpy
        if [[ ${TH_VERSION} == 1.0.1 ]] || [[ ${TH_VERSION} == 1.1.0 ]]; then
          pip install --quiet torch=="${TH_VERSION}" -f https://download.pytorch.org/whl/cpu/stable
        else
          pip install --quiet torch=="${TH_VERSION}+cpu" -f https://download.pytorch.org/whl/torch_stable.html
        fi
    - name: cmake
      env:
        CC: gcc-7
        CXX: g++-7
      run: mkdir build && cd build && cmake .. && make
    - name: pip install pytorch_binding
      env:
        CC: gcc-7
        CXX: g++-7
      run: cd pytorch_binding && python setup.py install
    - name: Test with pytest
      run: |
        pip install pytest
        pytest tests
